### ISSUE TITLE
Error in marking

### ISSUE THREAD

**Issue by xartuu** [FriendsOfFlarum/pages#2]
Hello!
Could you check one thing for me? I don't know if it's only me who has this error, but I can't tag users of the forum. After tagging `@Fajuu` and entering the page `/p/1`, an error pops up for me.
```
Failed to load resource: the server responded with a status of 500 ()               /api/pages/1:1
```
My page settings:
```
is_html = 0
is_hidden = 0
```
Could you see if it also occurs in you and possibly say why it happens?

**Comment by xartuu** [comment]
Film with a demonstration of an error.
https://www.youtube.com/watch?v=oPz_5ZX25oM

**Comment by dsevillamartin** [comment]
Seems to be an issue when passing the page through the formatter. Hm...

Error log, provided by @Trumeet. Same as in video with demonstration.

```php
[2019-01-20 17:27:49] production.ERROR: Error: Call to a member function find() on null in /flarum/app/vendor/flarum/mentions/src/Listener/FormatUserMentions.php:76
Stack trace:
#0 /flarum/app/vendor/s9e/text-formatter/src/Utils.php(61): Flarum\Mentions\Listener\FormatUserMentions->Flarum\Mentions\Listener\{closure}(Array)
#1 [internal function]: s9e\TextFormatter\Utils::s9e\TextFormatter\{closure}(Array)
#2 /flarum/app/vendor/s9e/text-formatter/src/Utils.php(63): preg_replace_callback('((<USERMENTION)...', Object(Closure), '<r><QUOTE><i>&g...')
#3 /flarum/app/vendor/flarum/mentions/src/Listener/FormatUserMentions.php(83): s9e\TextFormatter\Utils::replaceAttributes('<r><QUOTE><i>&g...', 'USERMENTION', Object(Closure))
#4 /flarum/app/vendor/illuminate/events/Dispatcher.php(350): Flarum\Mentions\Listener\FormatUserMentions->render(Object(Flarum\Formatter\Event\Rendering))
#5 /flarum/app/vendor/illuminate/events/Dispatcher.php(200): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Flarum\\Formatte...', Array)
#6 /flarum/app/vendor/flarum/core/src/Formatter/Formatter.php(78): Illuminate\Events\Dispatcher->dispatch('Flarum\\Formatte...')
#7 /flarum/app/vendor/fof/pages/src/Page.php(101): Flarum\Formatter\Formatter->render('<r><QUOTE><i>&g...', Object(FoF\Pages\Page))
#8 /flarum/app/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php(438): FoF\Pages\Page->getContentHtmlAttribute(NULL)
#9 /flarum/app/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php(340): Illuminate\Database\Eloquent\Model->mutateAttribute('content_html', NULL)
#10 /flarum/app/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php(313): Illuminate\Database\Eloquent\Model->getAttributeValue('content_html')
#11 /flarum/app/vendor/flarum/core/src/Database/AbstractModel.php(118): Illuminate\Database\Eloquent\Model->getAttribute('content_html')
#12 /flarum/app/vendor/illuminate/database/Eloquent/Model.php(1382): Flarum\Database\AbstractModel->getAttribute('content_html')
#13 /flarum/app/vendor/fof/pages/src/Api/Serializer/PageSerializer.php(26): Illuminate\Database\Eloquent\Model->__get('content_html')
#14 /flarum/app/vendor/flarum/core/src/Api/Serializer/AbstractSerializer.php(71): FoF\Pages\Api\Serializer\PageSerializer->getDefaultAttributes(Object(FoF\Pages\Page))
#15 /flarum/app/vendor/tobscure/json-api/src/Resource.php(169): Flarum\Api\Serializer\AbstractSerializer->getAttributes(Object(FoF\Pages\Page), NULL)
#16 /flarum/app/vendor/tobscure/json-api/src/Resource.php(75): Tobscure\JsonApi\Resource->getAttributes()
#17 /flarum/app/vendor/tobscure/json-api/src/Collection.php(123): Tobscure\JsonApi\Resource->toArray()
#18 [internal function]: Tobscure\JsonApi\Collection->Tobscure\JsonApi\{closure}(Object(Tobscure\JsonApi\Resource))
#19 /flarum/app/vendor/tobscure/json-api/src/Collection.php(124): array_map(Object(Closure), Array)
#20 /flarum/app/vendor/tobscure/json-api/src/Document.php(181): Tobscure\JsonApi\Collection->toArray()
#21 /flarum/app/vendor/tobscure/json-api/src/Document.php(224): Tobscure\JsonApi\Document->toArray()
#22 /flarum/app/vendor/flarum/core/src/Api/JsonApiResponse.php(29): Tobscure\JsonApi\Document->jsonSerialize()
#23 /flarum/app/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(113): Flarum\Api\JsonApiResponse->__construct(Object(Tobscure\JsonApi\Document))
#24 /flarum/app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flarum\Api\Controller\AbstractSerializeController->handle(Object(Zend\Diactoros\ServerRequest))
#25 /flarum/app/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Zend\Diactoros\ServerRequest), Array)
#26 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\DispatchRoute->process(Object(Zend\Diactoros\ServerRequest), Object(Closure))
#27 /flarum/app/vendor/flagrow/terms/src/Middlewares/RegisterMiddleware.php(59): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#28 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flagrow\Terms\Middlewares\RegisterMiddleware->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#29 /flarum/app/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#30 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\SetLocale->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#31 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#32 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#33 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(34): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#34 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#35 /flarum/app/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#36 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\RememberFromCookie->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#37 /flarum/app/vendor/flarum/core/src/Http/Middleware/StartSession.php(62): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#38 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\StartSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#39 /flarum/app/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(31): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#40 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#41 /flarum/app/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(29): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#42 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\ParseJsonBody->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#43 /flarum/app/vendor/flarum/core/src/Api/Middleware/HandleErrors.php(42): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#44 /flarum/app/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Api\Middleware\HandleErrors->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#45 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(91): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#46 /flarum/app/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#47 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\RequestHandler->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#48 /flarum/app/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#49 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePathRouter->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#50 /flarum/app/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#51 /flarum/app/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(78): Middlewares\BasePath->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\MiddlewarePipe))
#52 /flarum/app/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#53 /flarum/app/vendor/flarum/core/src/Http/Server.php(46): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#54 /flarum/app/public/index.php(22): Flarum\Http\Server->listen()
#55 {main}
```
